# fix iTerm2 - tmux - vim/nvim Alt/Option key issue
set -g xterm-keys on
set -ga terminal-overrides ',xterm-256color:Tc'

# Copy-paste integration {{{

# 'y' yanks selection to system clipboard and exits copy mode
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# 'Enter' copies selection to system clipboard (stays in copy mode)
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "pbcopy"

# }}}
